import React from 'react'
import { Link } from 'react-router-dom'
import Footer from '../components/Footer'

const LAST_UPDATED = '22 April 2026'

export default function TermsPage() {
  return (
    <div style={styles.page}>
      <div style={styles.main}>
        <div style={styles.topbar}>
          <Link to="/" style={styles.back}>← Cheatsheet</Link>
        </div>

        <h1 style={styles.title}>Terms of Service</h1>
        <p style={styles.updated}>Last updated: {LAST_UPDATED}</p>

        <section style={styles.section}>
          <h2 style={styles.h2}>1. Acceptance</h2>
          <p style={styles.p}>
            By using Cheatsheet Generator ("the Service"), you agree to these Terms of Service. If you do not agree, do not use the Service.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>2. The Service</h2>
          <p style={styles.p}>
            Cheatsheet Generator is a web-based tool that uses AI language models to convert study materials you upload (PDFs, documents, pasted text) into structured, printable cheatsheets. The Service is provided "as is" and is offered primarily for educational use.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>3. Accounts</h2>
          <p style={styles.p}>
            Certain features require an account. You are responsible for keeping your login credentials secure and for all activity under your account. You must be at least 13 years old to use the Service.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>4. Credits and Payments</h2>
          <p style={styles.p}>
            Use of AI-powered generation consumes "credits". New accounts receive a small number of free credits. Additional credits may be purchased in prepaid packs; see our <Link to="/pricing" style={styles.link}>Pricing</Link> page.
          </p>
          <p style={styles.p}>
            Payments are processed by Paddle.com Market Ltd. ("Paddle") acting as Merchant of Record. By completing a purchase you accept Paddle's checkout terms in addition to these Terms.
          </p>
          <p style={styles.p}>
            Credits do not expire. One credit entitles you to one successful cheatsheet generation. If a generation fails due to a technical error on our side, we will not deduct a credit.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>5. Refunds</h2>
          <p style={styles.p}>
            Unused credits can be refunded within 14 days of purchase by contacting <a href="mailto:fengyaontu@gmail.com" style={styles.link}>fengyaontu@gmail.com</a>. Credits that have already been consumed are non-refundable. Refunds are processed through Paddle and may take up to 10 business days to appear on your statement.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>6. User Content</h2>
          <p style={styles.p}>
            You retain all ownership rights to materials you upload ("User Content"). By uploading User Content, you grant us a limited, non-exclusive license to process it for the sole purpose of generating your cheatsheet. We do not use User Content to train AI models.
          </p>
          <p style={styles.p}>
            You represent that you have the right to upload all User Content and that it does not infringe any third-party rights.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>7. Acceptable Use</h2>
          <p style={styles.p}>
            You must not use the Service to:
          </p>
          <ul style={styles.ul}>
            <li>Upload content that is illegal, infringes intellectual property, or violates privacy of others</li>
            <li>Generate content intended to deceive, defame, or harass</li>
            <li>Circumvent rate limits, scrape the Service, or attempt to access accounts that are not yours</li>
            <li>Resell the Service or its output as your own AI product</li>
          </ul>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>8. AI-Generated Output</h2>
          <p style={styles.p}>
            Cheatsheets are generated by large language models and may contain errors, omissions, or inaccurate information. The Service is a study aid, not an authoritative source. You are responsible for verifying output before relying on it for exams, assignments, or any other purpose.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>9. Service Availability</h2>
          <p style={styles.p}>
            We aim to keep the Service available but do not guarantee uptime. Features, models, and pricing may change. We may suspend or terminate accounts that violate these Terms.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>10. Disclaimer of Warranties</h2>
          <p style={styles.p}>
            The Service is provided on an "as is" and "as available" basis. To the maximum extent permitted by law, we disclaim all warranties, express or implied, including merchantability, fitness for a particular purpose, and non-infringement.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>11. Limitation of Liability</h2>
          <p style={styles.p}>
            To the maximum extent permitted by law, our total liability for any claim arising out of or relating to the Service is limited to the amount you paid us in the 12 months preceding the claim.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>12. Changes to These Terms</h2>
          <p style={styles.p}>
            We may update these Terms. Material changes will be announced on this page; continued use after changes means you accept them.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>13. Contact</h2>
          <p style={styles.p}>
            Questions about these Terms: <a href="mailto:fengyaontu@gmail.com" style={styles.link}>fengyaontu@gmail.com</a>.
          </p>
        </section>
      </div>

      <Footer />
    </div>
  )
}

const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
  },
  main: {
    flex: 1,
    maxWidth: 720,
    width: '100%',
    margin: '0 auto',
    padding: '24px 20px',
  },
  topbar: {
    marginBottom: 32,
  },
  back: {
    fontSize: 14,
    color: '#57606a',
    textDecoration: 'none',
  },
  title: {
    fontSize: 34,
    margin: '0 0 8px',
    letterSpacing: '-0.02em',
  },
  updated: {
    fontSize: 13,
    color: '#8b949e',
    margin: '0 0 32px',
  },
  section: {
    marginBottom: 28,
  },
  h2: {
    fontSize: 19,
    margin: '0 0 10px',
    color: '#1f2328',
  },
  p: {
    margin: '0 0 10px',
    color: '#24292f',
    lineHeight: 1.65,
    fontSize: 15,
  },
  ul: {
    margin: '0 0 10px',
    paddingLeft: 22,
    color: '#24292f',
    lineHeight: 1.75,
    fontSize: 15,
  },
  link: {
    color: '#0969da',
    textDecoration: 'none',
  },
}
